theme: jekyll-theme-minimal

title: Hi, I'm Natalia. Welcome to my homepage!

description: This page will be used to showcase some of my personal projects as I attempt to further my coding knowledge.
